.phony: all

output = libsousvide.a

cpp_sources = \

c_sources = \
    owts.c \

cpp_flags = -I ./ -I ../src -Wall -std=c++14 -g -O0
c_flags = -I ./ -I ../src -Wall -std=gnu11 -g  -O0

cpp_objs_lib = $(addprefix objs_lib/,$(patsubst %.cpp,%.o,$(cpp_sources)))
c_objs_lib = $(addprefix objs_lib/,$(patsubst %.c,%.o,$(c_sources)))

all: pre $(output)

pre:
	mkdir -p objs_lib

clean:
	rm -rf objs_lib
	rm -f $(output)

objs_lib/%.o: %.c
	gcc -c $(c_flags) -o $@ $^

objs_lib/%.o: %.cpp
	g++ -c $(cpp_flags) -o $@ $^

$(output): $(c_objs_lib) $(cpp_objs_lib)
	ar rcs $(output) $^
